name: roll10000
description: "Dice game 10 000"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_localizations:
    sdk: flutter

  provider: ^6.1.2

  shared_preferences: ^2.2.2


  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/images/felt_texture.png
    - assets/dice/standard/
    - assets/dice/marked/

  # Lokaliseringsst√∏tte
  generate: true
  # Angi hvor .arb-filene ligger
l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
